render([
    group([
hide('cultivation_object_info-uid', ''),
showInput('学号', 'cultivation_object_info-UserId', '', '4'),
showInput('姓名', 'cultivation_object_info-name', '', '4'),
showInput('团支部ID', 'cultivation_object_info-league_branch_Id', '', '4'),
showInput('年级', 'cultivation_object_info-Grade', '', '4'),
showInput('性别', 'cultivation_object_info-sex', '', '4'),
showInput('民族', 'cultivation_object_info-natiion', '', '4'),
showInput('电话', 'cultivation_object_info-phone', '', '4'),
showInput('绩点', 'cultivation_object_info-point', '', '4'),
showTime('递交入党申请书时间', 'cultivation_object_info-join_application_time', '', '4'),
showFile('入党申请书', 'cultivation_object_info-join_application'),
hide('cultivation_object_info-Class', ''),
hide('cultivation_object_info-birthday', ''),
hide('cultivation_object_info-be_activist_time', ''),
hide('cultivation_object_info-graduation_time', ''),
hide('cultivation_object_info-rank', ''),
hide('cultivation_object_info-community_representation', ''),
hide('cultivation_object_info-development_object_time', ''),
hide('cultivation_object_info-join_party_time', ''),
hide('cultivation_object_info-party_Id', ''),
hide('cultivation_object_info-party_committee_eaxm_time', ''),
hide('cultivation_object_info-join_train_class_time', ''),
hide('cultivation_object_info-join_party_volunte',''),
hide('cultivation_object_info-sub_time_of_vlolunte', ''),
hide('cultivation_object_info-sub_formal_application_Time', ''),
hide('cultivation_object_info-formal_application',''),
hide('cultivation_object_info-formal_time', ''),
hide('cultivation_object_info-cultivation_object_stateId', ''),
hide('cultivation_object_info-alutobiography',''),
hide('cultivation_object_info-swear_time', ''),
hide('cultivation_object_info-qq', ''),
hide('cultivation_object_info-weixin', ''),
    ], '详情界面')], '', 'ecampus.join_party.cultivation_object_info@find&id=' + q.id, '', '详情');