render([
    group([
showInput('uid', 'cultivation_object_info-uid', '', '4'),
showInput('学号', 'cultivation_object_info-stu_Id', '', '4'),
showInput('姓名', 'cultivation_object_info-name', '', '4'),
showInput('班级', 'cultivation_object_info-Class', '', '4'),
showTime('递交入党申请书时间', 'cultivation_object_info-join_application_time', '', '4'),
showInput('性别', 'cultivation_object_info-sex', '', '4'),
showInput('民族', 'cultivation_object_info-natiion', '', '4'),
showInput('年级', 'cultivation_object_info-Grade', '', '4'),
showTime('出生年月', 'cultivation_object_info-birthday', '', '4'),
showInput('电话', 'cultivation_object_info-phone', '', '4'),
showInput('学历', 'cultivation_object_info-qualification', '', '4'),
showInput('团支部ID', 'cultivation_object_info-league_branch_Id', '', '4'),
showTime('确定为积极分子时间', 'cultivation_object_info-be_activist_time', '', '4'),
showTime('党校结业时间', 'cultivation_object_info-graduation_time', '', '4'),
showInput('绩点', 'cultivation_object_info-point', '', '4'),
showInput('排名', 'cultivation_object_info-rank', '', '4'),
showInput('社区表现分', 'cultivation_object_info-community_representation', '', '4'),
showTime('确定为发展对象时间', 'cultivation_object_info-development_object_time', '', '4'),
showTime('入党时间', 'cultivation_object_info-join_party_time', '', '4'),
showInput('党支部ID', 'cultivation_object_info-party_Id', '', '4'),
showTime('党委审批时间', 'cultivation_object_info-party_committee_eaxm_time', '', '4'),
showTime('预备党员培训时间', 'cultivation_object_info-join_train_class_time', '', '4'),
showFile('入党志愿书附件', 'cultivation_object_info-join_party_volunte'),
showTime('提交入党志愿书时间', 'cultivation_object_info-sub_time_of_vlolunte', '', '4'),
showTime('提交转正申请书时间', 'cultivation_object_info-sub_formal_application_Time', '', '4'),
showFile('转正申请附件', 'cultivation_object_info-formal_application'),
showTime('转正时间', 'cultivation_object_info-formal_time', '', '4'),
showInput('培养对象状态ID', 'cultivation_object_info-cultivation_object_stateId', '', '4'),
showFile('个人自传附件', 'cultivation_object_info-alutobiography'),
showTime('宣誓时间', 'cultivation_object_info-swear_time', '', '4'),
showInput('qq号', 'cultivation_object_info-qq', '', '4'),
showInput('微信号', 'cultivation_object_info-weixin', '', '4'),
showFile('入党申请书', 'cultivation_object_info-join_application')
],'标题')],'','ecampus.join_party.cultivation_object_info@find&id='+q.id,'','详情');